name: Build and deploy container app to Azure Web App - msvc-security

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-msvc-security:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DAD61F73CEA749AB9B8DD66A3A8EE796 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_16D40B8D29C94F9DA4FABD67BB0B9097 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EE2CFD28F8F4186958D68D7CD8323B2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'msvc-security'
          slot-name: 'Production'
          images: "${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-msvc-security:latest"
          